apiVersion: v1
kind: Pod
metadata:
  labels:
    app: web
  name: simple-webapp-color
spec:
  containers:
  - env:
    - name: APP_COLOR
      value: red
    image: mmumshad/simple-webapp-color
    name: simple-webapp-color
    ports:
    - containerPort: 8080
